### ISSUE TITLE
check_mk and pi-hole

### ISSUE THREAD

**Issue by chris240189** [chrisss404/check-mk-arm#12]
I was trying to use check_mk and pi-hole on the same RPi3 3B+, but it looks like they don't like each other.

I played a bit with the lighttpd conf etc. but it seems either one or the other breaks or atleast the web-gui.

Do you have any experience with that? Could check_mk be made compatible? Is there even enough power on a RPi3 B+ to make both work simultaneously?

**Comment by chrisss404** [comment]
This issue is a bit off-topic, but let's see if I can help you.

https://discourse.pi-hole.net/t/hardware-software-requirements/273
> Port 80 should be used by lighttpd
> 
> If you have another Web server already running, such as Apache, Pi-hole’s Web server will not work. You can either disable the other Web server or change the port on which lighttpd listens, which allows you keep both Web servers running.

The problem you are facing is that two web servers compete for port 80. So you can configure one of them to use a different port, or you can get rid of one of them.

I would suggest the second solution: getting rid of lighttpd. For more information, see: https://discourse.pi-hole.net/t/migrating-pi-hole-from-lighttpd-to-apache/152/4.

    # Stop and disable lighttpd service
    systemctl stop lighttpd.service
    systemctl disable lighttpd.service

    # Get PHP support for apache2
    apt-get install libapache2-mod-php

    # Restart apache2 service
    systemctl restart apache2.service

I think in terms of performance, there should not be any problems for your RPi.

HTH & BR
Christian
