### ISSUE TITLE
no updates for stretch anymore?

### ISSUE THREAD

**Issue by daeks** [chrisss404/check-mk-arm#13]
Hi chrisss404,

will there be also updates for stretch or is the support dropped on it? :(

**Comment by chrisss404** [comment]
Hi daeks,

I'm sorry, there are no more updates for Stretch. That's just because I do not have enough resources and time to provide packages for Stretch and Buster.

However, if you don't want to upgrade your Raspian to the latest version for whatever reason and still want to have the latest version of Check_MK, you can build your own package. It's easy. You only have to do the following:

    git clone https://github.com/chrisss404/check-mk-arm
    cd check-mk-arm
    git checkout b9dd2bb
    bash build_check_mk.sh 1.5.0p21

BR
Christian
