### ISSUE TITLE
Memory usage over 80%..

### ISSUE THREAD

**Issue by ZXRobotum** [chrisss404/check-mk-arm#48]
Hello,
i had a small question about Memory Usage on CheckMK.

I installed your last Version 2.0.0p20 on my Raspberry and after them, i see, that the memory usage is over 80& every time. What kind of problems ist that and how can i solve this issue?

Best regards

Z. Matthias

**Comment by chrisss404** [comment]
Hey Matthias,

this can have many causes. Which PI and which OS are you using?

If it is a Pi 3, I recommend not to use the 64bit packages due to its limited resources, see: #44

BR
Christian

**Comment by ZXRobotum** [comment]
Hey Christian,
Thank you very much for your help.

Yesterday I took another look at my CheckMK server.

It is a Raspi PI4 with 4GB HDD and a 128GB FlashCard. It is actually very fast in this version. 
But unfortunately I had to realise that somehow with Bullseye on 32bit it didn't really cope with the installations / updates of CheckMK. In the end, the CPU load increased just as much as the memory requirement.

Today I reinstalled UBUNTU 21.10 (Impish-Indri) (with a new flash card, also with 128 GB) and installed your image. The installation was interrupted because dpkg found that some programmes were missing, such as Apache & Co. I then installed all the programmes it listed by hand and then continued with the installation of CheckMK.
In the process, I really had to realise that there are a few things that have to be done differently in this version than in the previous one. Maybe that's why my old installation went on strike or something.

Now the load on the PI4 is 15% CPU load and 24% memory load. These are the areas that I like better. 

Have you actually already tried the new UBUNTU? Is the change worth it & can I do it without problems with this CheckMK version?

Bet regards

Z. Matthias

**Comment by martux69** [comment]
Hi @ZXRobotum ,
I used Ubuntu 21.10 for two week nows (after a do-release-upgrade from hirsute) and have no problems with running checkmk. Installation of the build deps worked without failure and my memory consumption with a 8GB Pi4 is 17%:
`System information as of Wed Mar  9 20:30:17 CET 2022

  System load:              0.54
  Usage of /:               36.2% of 221.05GB
  Memory usage:             17%
  Swap usage:               0%
  Temperature:              48.2 C
  Processes:                172`
`free -m
               total        used        free      shared  buff/cache   available
Mem:            7808         808         727          11        6272        6675
Swap:           8191          18        8173
`
As soon as the next Ubuntu LTS version is released (should be at April 21, 2022), I will try to build a checkmk version for it.
Since today there is also a 64-bit bullseye available, build from me, tested by other users.

Kind regards
Martin

**Comment by ZXRobotum** [comment]
Hello Martin,

I have been using Ubuntu 21.10 on my Raspberry Pi4 with 4GB for a good 3 days now.

The load on it is just as low as on yours:

System Load: 1,91
Memory Usage: 20,2%
Swap Usage: 0%

               total        used        free      shared  buff/cache   available
Mem:            3791        1006         377          11        2407        2578
Swap:           7999           0        7999

So, I am willing to test the new version together with the new UBUNTU. I would be really happy about that. I personally love DEBIAN, but the 64bit was not yet available, which was not so bad. The only problem last time was that somehow the updates didn't implement themselves properly and so I had some problems with this machine. Now I prefer to leave it and that's good. For the CLOUD computers, I am currently setting up an x86 server with an official version. What I would like to try then is the connection to the Raspberry Pi4. So, if I can help with anything, please just let me know. I will then also update the OS version. Or can I do that earlier?
Best regards

Matthias
